import {firebaseEnabled,api} from './firebase.js';import {saveTest,tests,currentUser,setLocalEmail} from './store.js';
const WORDS=`about after again against almost always animal answer around because before between black book both bring build called came change city close could country course day different does down early earth enough even every example family few find first following food found four from game general give good great group hand hard have help here high home house important into just keep kind know large last later learn left life light like line little long look made make many might more most move much must name near need never new next night number often once only open other over own part people place point put question right same school seem should show small something sometimes sound still such system take than that their them then these thing think those three through time together too under until use used very want water way well what when where which while white who whole will with without word work world would write year young your`.split(' ');
const e={win:document.querySelector('#typingWindow'),input:document.querySelector('#typingInput'),stream:document.querySelector('#wordStream'),caret:document.querySelector('#caret'),time:document.querySelector('#timeLeft'),wpm:document.querySelector('#liveWpm'),results:document.querySelector('#results'),rw:document.querySelector('#resultWpm'),ra:document.querySelector('#resultAccuracy'),rc:document.querySelector('#resultChars'),re:document.querySelector('#resultErrors'),hint:document.querySelector('.typing-hint')};let duration=30,started=false,finished=false,startAt=0,timer,current=0,typed='',errors=0,correct=0,total=0,clicks=0,clickTimer,wordList=[];
function build(){wordList=Array.from({length:180},()=>WORDS[Math.random()*WORDS.length|0]);e.stream.innerHTML=wordList.map((w,i)=>`<span class="word ${i?'':'current'}">${[...w].map(c=>`<span class="letter">${c}</span>`).join('')}</span>`).join('');requestAnimationFrame(caret)}
function focus(){try{e.input.focus({preventScroll:true})}catch{e.input.focus()}window.scrollTo({top:Math.max(0,e.win.getBoundingClientRect().top+scrollY-100),behavior:'instant'})}
function caret(){const w=e.stream.children[current];if(!w)return;const ls=w.querySelectorAll('.letter'),t=ls[Math.min(typed.length,ls.length-1)],r=e.win.getBoundingClientRect(),q=(t||w).getBoundingClientRect();e.caret.style.transform=`translate(${(t?q.left:q.right)-r.left}px,${q.top-r.top+1}px)`;const y=q.top-r.top;if(y>105||y<30)e.stream.style.transform=`translateY(${-Math.max(0,y-52)}px)`}
function start(){if(started||finished)return;started=true;startAt=Date.now();e.hint.classList.add('hidden');timer=setInterval(tick,100)}function tick(){const sec=(Date.now()-startAt)/1000,left=Math.max(0,duration-sec);e.time.textContent=Math.ceil(left);e.wpm.textContent=Math.round(correct/5/Math.max(sec/60,1/60));if(!left)finish()}
function input(){if(finished)return;start();const v=e.input.value;if(v.endsWith(' ')){const entered=v.slice(0,-1),target=wordList[current];total+=Math.max(entered.length,target.length);for(let i=0;i<Math.max(entered.length,target.length);i++)entered[i]===target[i]?correct++:errors++;e.stream.children[current]?.classList.remove('current');e.stream.children[current]?.classList.add('done');current++;typed='';e.input.value='';e.stream.children[current]?.classList.add('current')}else{typed=v;const w=e.stream.children[current];w?.querySelectorAll('.letter').forEach((l,i)=>{l.classList.toggle('correct',i<typed.length&&typed[i]===l.textContent);l.classList.toggle('wrong',i<typed.length&&typed[i]!==l.textContent)})}caret()}
async function finish(){if(finished)return;finished=true;clearInterval(timer);const sec=Math.max((Date.now()-startAt)/1000,1),wpm=Math.round(correct/5/(sec/60)),acc=total?Math.max(0,Math.round(correct/total*100)):0;e.rw.textContent=wpm;e.ra.textContent=acc+'%';e.rc.textContent=correct;e.re.textContent=errors;e.results.classList.remove('hidden');await saveTest({wpm,accuracy:acc,chars:correct,errors,duration});loadStats()}
function restart(){clearInterval(timer);started=false;finished=false;startAt=0;current=0;typed='';errors=0;correct=0;total=0;e.time.textContent=duration;e.wpm.textContent=0;e.input.value='';e.results.classList.add('hidden');e.hint.classList.remove('hidden');e.stream.style.transform='translateY(0)';build();focus()}
function setDuration(v){duration=+v;document.querySelectorAll('[data-time]').forEach(b=>b.classList.toggle('selected',+b.dataset.time===duration));restart()}
async function loadStats(){const t=await tests(),best=t.length?Math.max(...t.map(x=>x.wpm||0)):0,avg=t.length?Math.round(t.reduce((a,x)=>a+(x.wpm||0),0)/t.length):0,acc=t.length?Math.round(t.reduce((a,x)=>a+(x.accuracy||0),0)/t.length):0;document.querySelector('#bestWpm').textContent=best;document.querySelector('#avgWpm').textContent=avg;document.querySelector('#avgAccuracy').textContent=acc+'%';document.querySelector('#testCount').textContent=t.length;document.querySelector('#recentTests').innerHTML=t.slice(0,10).map(x=>`<div class="recent-row"><span>${x.duration||30}s test</span><span>${x.wpm||0} wpm</span><span>${x.accuracy||0}%</span><span>${x.errors||0} errors</span></div>`).join('')||'<p class="muted">No tests yet.</p>'}
let signup=false;const modal=document.querySelector('#authModal');function authMode(){document.querySelector('#authTitle').textContent=signup?'create account':'log in';document.querySelector('#authSubmit').textContent=signup?'create account':'log in';document.querySelector('#toggleAuth').textContent=signup?'back to log in':'create an account'}
async function auth(ev){ev.preventDefault();const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,s=document.querySelector('#authStatus');s.textContent='';try{if(firebaseEnabled){if(signup)await api.createUserWithEmailAndPassword(api.auth,email,password);else await api.signInWithEmailAndPassword(api.auth,email,password)}else setLocalEmail(email);modal.classList.add('hidden');updateAccount()}catch(x){s.textContent=x.message.replace('Firebase: ','')}}
async function updateAccount(){const u=await currentUser();document.querySelector('#accountBtn').textContent=u?(u.email||'account'):'log in'}
document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>setDuration(b.dataset.time));document.querySelector('#restartBtn').onclick=restart;document.querySelector('#resultRestart').onclick=restart;e.win.onclick=focus;e.input.oninput=input;e.win.addEventListener('click',()=>{clicks++;clearTimeout(clickTimer);clickTimer=setTimeout(()=>clicks=0,1000);if(clicks>=5)location.href='games.html'});document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth'}));document.querySelector('#accountBtn').onclick=()=>modal.classList.remove('hidden');document.querySelector('#closeModal').onclick=()=>modal.classList.add('hidden');document.querySelector('#toggleAuth').onclick=()=>{signup=!signup;authMode()};document.querySelector('#authForm').onsubmit=auth;document.querySelector('#exportBtn').onclick=async()=>{const blob=new Blob([JSON.stringify(await tests(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='jonnytype-data.json';a.click()};build();restart();updateAccount();loadStats();
